const SET_PLAYING_NOW_MOVIES = 'SET_PLAYING_NOW_MOVIES';
const SET_POPULAR_MOVIES = 'SET_POPULAR_MOVIES';
const SET_TOP_RATED_MOVIES = 'SET_TOP_RATED_MOVIES';
const SET_UPCOMING_MOVIES = 'SET_UPCOMING_MOVIES';
const ADD_MOVIE_TO_FAVORITES = 'ADD_MOVIE_TO_FAVORITES';
const SET_FAVOURITE_MOVIES = 'SET_FAVOURITE_MOVIES';
const REMOVE_FAVOURITE_MOVIES = 'REMOVE_FAVOURITE_MOVIES';

const types = {
    SET_PLAYING_NOW_MOVIES,
    SET_POPULAR_MOVIES,
    SET_TOP_RATED_MOVIES,
    SET_UPCOMING_MOVIES,
    ADD_MOVIE_TO_FAVORITES,
    SET_FAVOURITE_MOVIES,
    REMOVE_FAVOURITE_MOVIES,
};

export default types;
